// <auto-generated />
using CooperativaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CooperativaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250403212212_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CooperativaAPI.Models.Entities.ContatoFavorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CooperadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoChavePix")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CooperadoId");

                    b.ToTable("ContatosFavoritos");
                });

            modelBuilder.Entity("CooperativaAPI.Models.Entities.Cooperado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ContaCorrente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CooperativaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CooperativaId");

                    b.ToTable("Cooperados");
                });

            modelBuilder.Entity("CooperativaAPI.Models.Entities.Cooperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cooperativas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Cooperativa A"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Cooperativa B"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Cooperativa C"
                        });
                });

            modelBuilder.Entity("CooperativaAPI.Models.Entities.ContatoFavorito", b =>
                {
                    b.HasOne("CooperativaAPI.Models.Entities.Cooperado", "Cooperado")
                        .WithMany("ContatosFavoritos")
                        .HasForeignKey("CooperadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperado");
                });

            modelBuilder.Entity("CooperativaAPI.Models.Entities.Cooperado", b =>
                {
                    b.HasOne("CooperativaAPI.Models.Entities.Cooperativa", "Cooperativa")
                        .WithMany("Cooperados")
                        .HasForeignKey("CooperativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cooperativa");
                });

            modelBuilder.Entity("CooperativaAPI.Models.Entities.Cooperado", b =>
                {
                    b.Navigation("ContatosFavoritos");
                });

            modelBuilder.Entity("CooperativaAPI.Models.Entities.Cooperativa", b =>
                {
                    b.Navigation("Cooperados");
                });
#pragma warning restore 612, 618
        }
    }
}
